---
- name: Display Node.js and npm versions
  hosts: localhost 
  connection: local
  gather_facts: false
  tasks:
    - name: Display Node.js version
      command: node -v
      register: node_version

    - name: Display npm version
      command: npm -v
      register: npm_version

    - name: Print Node.js version
      debug:
        var: node_version.stdout

    - name: Print npm version
      debug:
        var: npm_version.stdout

